### ISSUE TITLE
[Low Priority][Bug] Does not show recipe when it can be crafted on multiple crafting tables.

### ISSUE THREAD

**Issue by MilkMC** [CraftedMods/jei-lotr#1]
High Elven Wood Bars and High Elven Steel Bars can both be crafted on either the Lindon or RIvendell crafting table. JEI does not display these recipes, although it does display the other recipes for those tables.

Edit: High Elven, Haradric, and Red Haradric pillars and pillar slabs are some more example.

As a side note, is it possible to prioritize faction crafting tables over the "anvil recipes" so that the faction crafting recipes are shown first? It is slightly annoying to have to click the arrow everytime you want to see a recipe for equipment or armor.

Thanks for all the work you do. It really is appreciated.

**Comment by CraftedMods** [comment]
1.) Seems like a bug, I've to look into that
2.) The latest release of NEI Recipe Handlers added exactly that, but now we're at 1.15.2, and JEI currently doesn't support that. I'll probably create a PR for JEI in the future, which exactly allows that.
